name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_ID: 'ghcr.io/dimantchick/spring-telegram-bot:latest'

jobs:

  build-docker-image:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_ID }} --build-arg APP_NAME=spring-telegram-bot-1.0-SNAPSHOT

    - name: Push image to GitHub Container Registry
      run: docker push ${{ env.IMAGE_ID }}
